### ISSUE TITLE
openvpn的流量能否检测出来？

### ISSUE THREAD

**Issue by ghost** [nursery01/GFW-system#1]
我使用的是openvpn udp协议，tls1.3加密，chacha20-polay1305 sha512.

**Comment by nursery01** [comment]
openvpn幾年前就被gfw識別了，但是你有一個不一樣的地方就是你用了udp，如果我沒錯的話當前gfw對udp查的沒tcp那麽嚴，並不是查不出來，未來會不會查的更嚴我就不知道了

你能穩定連得上就用，沒什麼可焦慮的

**Comment by ghost** [comment]
> 嚴

那里面的流量会被解密吗？我使用的是最新的加密，之前udp被封过端口

**Comment by nursery01** [comment]
如果用目前的電腦破解，10000年內不會被破解成功，如果是旁路方式的話，🧐

美國政府和銀行都在用tls，你的個人資訊不會比美國政府更值得破解
